syntax = "proto3";
package evmos.v9.callback;

import "gogoproto/gogo.proto";
import "callback/params.proto";
import "callback/test_data.proto";
// this line is used by starport scaffolding # genesis/proto/import

option go_package = "github.com/evmos/evmos/v9/x/callback/types";

// GenesisState defines the callback module's genesis state.
message GenesisState {
  Params params = 1 [(gogoproto.nullable) = false];
  repeated TestData testDataList = 2 [(gogoproto.nullable) = false];
  uint64 testDataCount = 3;
  // this line is used by starport scaffolding # genesis/proto/state
}
