syntax = "proto3";
package evmos.v9.callback;

// this line is used by starport scaffolding # proto/tx/import

option go_package = "github.com/evmos/evmos/v9/x/callback/types";

// Msg defines the Msg service.
service Msg {
      rpc CallEvmAdd(MsgCallEvmAdd) returns (MsgCallEvmAddResponse);
// this line is used by starport scaffolding # proto/tx/rpc
}

message MsgCallEvmAdd {
  string creator = 1;
  string contractAddress = 2;
  string funcName = 3;
  string arg = 4;
}

message MsgCallEvmAddResponse {
  uint64 result = 1;
}

// this line is used by starport scaffolding # proto/tx/message
